### ISSUE TITLE
Readme file or instruction for install

### ISSUE THREAD

**Issue by xuanlocle** [docsion/uppls#1]
I downloaded a file named `Docsion 0.3.6.dmg`. Double click on it and I drag docsion icon to application icon.
After that I run `Docsion` by spotlight search but it just show malware and move to trash.
Life's terrible

**Comment by beastoin** [comment]
Thanks God, Docsion have been checked for malicious software by Apple, just download and enjoy [https://docsion.com/download](https://docsion.com/download). 

Futhuremore, you can verify the binary by using SHA256 = 7439d882acb3eaf407882d48b5250504bc41adcb68fc44e930eaa4450e472332

<img width="264" alt="Screen Shot 2020-09-17 at 1 25 42 AM" src="https://user-images.githubusercontent.com/4256921/93379247-c5248600-f887-11ea-9e73-71dce56b4eea.png">

Regardless
