### ISSUE TITLE
What's different btw "Add an API" and "New API"?

### ISSUE THREAD

**Issue by thanhnh98** [docsion/uppls#10]
I was shock when i saw that

**Comment by beastoin** [comment]
Hey mate, actually, it's the best practice, you can see attachment to understand more about the simple rule:
1/ Never make user think

![Screen Shot 2020-11-11 at 9 33 28 AM](https://user-images.githubusercontent.com/4256921/98758460-79aed400-2401-11eb-968f-8693ce9ee403.png)

Thanks for using Docsion & regardless
Keep going pls
Thịnh
