### ISSUE TITLE
I can't read my API body

### ISSUE THREAD

**Issue by thanhlamqwe** [docsion/uppls#14]
I can't read my API body, Sir !!!!!!
**please format API Body in vertical 
please format API Body in vertical 
please format API Body in vertical 
please format API Body in vertical 
please format API Body in vertical 
please format API Body in vertical** 

![Screen Shot 2020-11-23 at 10 30 39](https://user-images.githubusercontent.com/58394256/99927179-f1242200-2d76-11eb-9af8-565c489d6903.png)

**Comment by beastoin** [comment]
Hi mate, pls share me your doc or send me curl, my email ngocthinhdp@gmail.com

--enjoy ❤️

**Comment by thanhlamqwe** [comment]
> Hi mate, pls share me your doc or send me curl, my email [ngocthinhdp@gmail.com](mailto:ngocthinhdp@gmail.com)
> 
> --enjoy ❤️

`curl --request GET https://api.opendota.com/api/heroes`
![Screen Shot 2020-11-23 at 14 44 09](https://user-images.githubusercontent.com/58394256/99938449-62290100-2d9a-11eb-97a6-a2f7ebc5b41b.png)`
this is what I expect next patch. love your work <3

**Comment by beastoin** [comment]
Hey mate, problem solved @ Docsion [v0.6.2,](https://github.com/docsion/uppls/#docsion-macos-062-prettify-json-response) enjoy ❤️

**Comment by thanhlamqwe** [comment]
I can't believe you fix this problem super fast after my report. Im downloading new docsion with my happy face. 
your work is perfect. now I can easy read my API in vertical. the text color good too.
you're the best. 
Keep it on and have a nice day Sir !!
![Screen Shot 2020-11-25 at 11 51 38](https://user-images.githubusercontent.com/58394256/100184663-96283180-2f14-11eb-8b39-736f30c38f49.png)
!
