### ISSUE TITLE
Response selectable

### ISSUE THREAD

**Issue by xuanlocle** [docsion/uppls#15]
Hi there,

After send request, I want to do more action with it. Same as select some text and copy them.

<img width="519" alt="Screen Shot 2020-12-31 at 1 28 08 PM" src="https://user-images.githubusercontent.com/19778140/103397696-06595100-4b6c-11eb-9e26-16cd91627a11.png">

**Comment by beastoin** [comment]
Hey mate, your wish come true on Docsion 0.7..3 https://github.com/docsion/uppls#06-jan-2021-docsion-v073-playground-response-collapsed-selectable ~~ enjoy 🚀
