### ISSUE TITLE
[Bug] White screen when open app

### ISSUE THREAD

**Issue by NguyenHuy1812** [docsion/uppls#19]
Quick note:
 - Using 2 screen mode, open the app on the main screen.
 - Open the app response only white screen.
 - Try to close/kill/open many times but still can't work.
 - Stop 1 screen, open the app success.
 - Using 2 screens again, open app success.
 
Not sure is that a Bug or not, if have any further information I will keep update in this.

**Comment by beastoin** [comment]
Yah, it's a bug, will fixed

**Comment by beastoin** [comment]
#17

**Comment by beastoin** [comment]
Bug fixed @ https://github.com/docsion/uppls#05-jan-2021-docsion-v072 ~~enjoy 🚀
