### ISSUE TITLE
Bug là Bug Diệt

### ISSUE THREAD

**Issue by thanhnh98** [docsion/uppls#22]
```{
    "page": 1,
    "per_page": 20,
    "photos": [
        {
            "id": 33041,
            "width": 4167,...```
-> **_Bug json format at line 4_** 
            
**The feature  i wish** -> ```COPY Response```

**Comment by thanhnh98** [comment]
:'( markdown failed

**Comment by beastoin** [comment]
Hey @thanhnh98 pls share me the doc, my email ngocthinhdp@gmail.com ~~yoo

**Comment by thanhnh98** [comment]
yup, i just invited you on Docsion, pls check yours

**Comment by beastoin** [comment]
hey mates, bug goaway on Docsion 0.7.3 https://github.com/docsion/uppls#06-jan-2021-docsion-v073-playground-response-collapsed-selectable ~~enjoy 🚀
