### ISSUE TITLE
Blank page after press ESC

### ISSUE THREAD

**Issue by ryenguyen7411** [docsion/uppls#3]
On main screen, I pressed ESC on my keyboard and it shown a blank page. Now I cannot go back from there.

Is this a feature? If yes then it's super cool :D If it's not the case, please fix it because my life depend on it.

I've attached a short videos below:
[Screen Recording 2020-09-17 at 16.24.56.mov.zip](https://github.com/docsion/bugpls/files/5237981/Screen.Recording.2020-09-17.at.16.24.56.mov.zip)

**Comment by beastoin** [comment]
Hey @ryenguyen7411 , thanks for using Docsion & sorry for leting you wait so long. Of course, it/s lovely 🐛 :)) , now, you can download the latest version @ Docsion 0.3.8, and look how nice that bug flying. 

- Link: [https://get.docsion.com](https://get.docsion.com/releases/Docsion%200.3.8.dmg)
- Version: 0.3.8+7
- SHA256: bc9b38aecc52423274b00cda9f41560a09911c1349a6ebaa889a009087d49892
