### ISSUE TITLE
[Sharing feature] Sharing a specific API but all shared

### ISSUE THREAD

**Issue by NguyenHuy1812** [docsion/uppls#5]
I just want to share a specific API doc with my friend, but all my docs are shared.

Besides that, please give a `DELETE` button, I have many duplicate docs and want to remove them, but I can't.

**Comment by beastoin** [comment]
1/ Bug fixed @ 0.5.3 version https://github.com/docsion/uppls/blob/master/README.md
2/ Follow https://github.com/docsion/uppls/issues/11 

Thanks & regardless,
Thinh
