### ISSUE TITLE
Sign in with apple not working

### ISSUE THREAD

**Issue by xuanlocle** [docsion/uppls#8]
I'm getting blank screen and can't back:

Is it even any fallback to use sign in with apple such as navigate back?

Version 0.5.2 (13)

**Comment by beastoin** [comment]
Hey mate, currently, Login with Apple feature have been dropped from @ Docsion v0.6.1, so, in-case you still need this feature, still re-open with the feature label @ enjoy ❤️ , Try new ver now https://github.com/docsion/uppls
