### ISSUE TITLE
Redundant redirect after sign in with google success

### ISSUE THREAD

**Issue by xuanlocle** [docsion/uppls#9]
After I signed in by google, my browser redirect to 

`http://127.0.0.1:13975/?state=...`

I think this is redundant action. It should be your app's homepage, something useful to the user or at least close it!

**Comment by beastoin** [comment]
Hey mate, now we get the meaningful redirect page https://jmp.sh/Sbg71wI @ https://github.com/docsion/uppls/#05-jan-2021-docsion-v072 ~~enjoy 🚀
